import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { UploadCloud, FileText, Layout, Image as ImageIcon, Mic, CheckCircle2, ChevronRight, Loader2, Sparkles } from 'lucide-react';

export default function Generator() {
  const navigate = useNavigate();
  const [step, setStep] = useState(0); // 0: upload, 1: parse, 2: structure, 3: visual, 4: voice, 5: done
  const [file, setFile] = useState(null);
  
  const steps = [
    { id: 1, title: 'Document Parser', icon: FileText, desc: 'Ingesting policies & manuals', color: 'text-blue-500' },
    { id: 2, title: 'Content Structuring', icon: Layout, desc: 'LLM creates modules', color: 'text-purple-500' },
    { id: 3, title: 'Visualizer', icon: ImageIcon, desc: 'Text-to-Image generation', color: 'text-emerald-500' },
    { id: 4, title: 'Voice Coach', icon: Mic, desc: 'TTS narration rendering', color: 'text-rose-500' }
  ];

  const handleFileUpload = (e) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
    }
  };

  const startGeneration = () => {
    if (!file) return;
    setStep(1);
  };

  useEffect(() => {
    if (step > 0 && step <= 4) {
      const timer = setTimeout(() => {
        setStep(prev => prev + 1);
      }, 3000); // 3 seconds per step for simulation
      return () => clearTimeout(timer);
    } else if (step === 5) {
      // Generation complete, save to localStorage
      const newCourseId = `course-${Date.now()}`;
      const newCourse = {
        id: newCourseId,
        title: file ? file.name.replace(/\.[^/.]+$/, "") + " Training" : "New AI Training Module",
        description: "Generated by CorpTrain AI from " + (file?.name || "document"),
        date: new Date().toISOString(),
        duration: "10 min",
        chapters: [
          {
            title: "Introduction to Policies",
            text: "Welcome to the corporate training module. In this section, we will cover the foundational policies that guide our workplace culture. It is essential to understand these guidelines to ensure a safe, productive, and inclusive environment.",
            explanation: "Hello and welcome to your corporate training journey! In this first section, we're going to talk about something really important: the foundational policies that shape our daily workplace culture. Now, I know reading through guidelines can sometimes feel a bit dry, but understanding these rules is absolutely essential. They aren't just red tape; they exist to make sure every single one of us has a safe, productive, and truly inclusive environment to work in every day.",
            imageUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
          },
          {
            title: "Code of Conduct",
            text: "Our Code of Conduct outlines the expected behavior for all employees. This includes mutual respect, integrity in our operations, and adherence to all compliance regulations. Please review the detailed guidelines carefully.",
            explanation: "Next up is our Code of Conduct. Think of this as the playbook for how we treat each other. It clearly outlines the behavior expected from everyone on the team. The biggest takeaways here are mutual respect and acting with absolute integrity in everything we do. It also touches on some strict compliance regulations we all have to follow by law. I encourage you to take a few minutes later to review the detailed document, but the golden rule is simple: treat others the way you want to be treated, and always do the right thing.",
            imageUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
          }
        ]
      };
      
      const existing = JSON.parse(localStorage.getItem('corp_train_courses') || '[]');
      localStorage.setItem('corp_train_courses', JSON.stringify([newCourse, ...existing]));
      
      setTimeout(() => {
        navigate(`/player/${newCourseId}`);
      }, 1500);
    }
  }, [step, file, navigate]);

  return (
    <div className="max-w-4xl mx-auto py-8 animate-in fade-in duration-500">
      <div className="text-center mb-10">
        <div className="inline-flex items-center justify-center p-3 bg-brand-100 text-brand-600 dark:bg-brand-900/30 dark:text-brand-400 rounded-full mb-4">
          <Sparkles size={28} />
        </div>
        <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-3">AI Module Generator</h1>
        <p className="text-slate-500 dark:text-slate-400 max-w-xl mx-auto">
          Upload your HR documents or training manuals, and our multi-agent pipeline will automatically create an engaging, interactive audio-visual module.
        </p>
      </div>

      <div className="glass-card rounded-3xl p-8 md:p-12 shadow-2xl border-white/50 dark:border-white/10 relative overflow-hidden">
        {step === 0 ? (
          <div className="text-center">
            <div className="border-2 border-dashed border-slate-300 dark:border-slate-600 rounded-2xl p-12 transition-all hover:border-brand-500 hover:bg-brand-50/50 dark:hover:bg-brand-900/10">
              <input
                type="file"
                id="file-upload"
                className="hidden"
                accept=".pdf,.doc,.docx,.txt"
                onChange={handleFileUpload}
              />
              <label htmlFor="file-upload" className="cursor-pointer flex flex-col items-center">
                <div className="bg-brand-100 dark:bg-brand-900/40 p-4 rounded-full text-brand-600 dark:text-brand-400 mb-4">
                  <UploadCloud size={40} />
                </div>
                <h3 className="text-xl font-semibold text-slate-800 dark:text-white mb-2">
                  {file ? file.name : 'Upload Training Document'}
                </h3>
                <p className="text-sm text-slate-500 dark:text-slate-400">
                  Drag and drop or click to browse (PDF, DOCX, TXT)
                </p>
              </label>
            </div>

            <button
              onClick={startGeneration}
              disabled={!file}
              className={`mt-8 flex items-center justify-center gap-2 w-full md:w-auto md:px-12 py-4 rounded-xl font-bold text-lg transition-all ${
                file 
                ? 'bg-brand-600 hover:bg-brand-500 text-white shadow-lg shadow-brand-500/30 hover:scale-105' 
                : 'bg-slate-200 dark:bg-slate-700 text-slate-400 cursor-not-allowed'
              } mx-auto`}
            >
              Generate AI Course
              <ChevronRight size={20} />
            </button>
          </div>
        ) : (
          <div className="py-4">
            <h2 className="text-2xl font-bold text-center mb-12 text-slate-800 dark:text-white">
              {step === 5 ? "Generation Complete!" : "AI Agents at Work..."}
            </h2>
            
            <div className="space-y-6 relative before:absolute before:inset-0 before:ml-6 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-slate-200 dark:before:via-slate-700 before:to-transparent">
              {steps.map((s, idx) => {
                const isActive = step === idx + 1;
                const isDone = step > idx + 1;
                
                return (
                  <div key={s.id} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
                    <div className={`flex items-center justify-center w-12 h-12 rounded-full border-4 border-white dark:border-[#1e293b] shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 ${
                      isActive ? `bg-white dark:bg-slate-800 ${s.color} animate-pulse-slow` :
                      isDone ? 'bg-brand-500 text-white' :
                      'bg-slate-100 dark:bg-slate-800 text-slate-300 dark:text-slate-600'
                    }`}>
                      {isDone ? <CheckCircle2 size={24} /> : <s.icon size={isActive ? 24 : 20} className={isActive ? 'animate-bounce' : ''} />}
                    </div>
                    
                    <div className={`w-[calc(100%-4rem)] md:w-[calc(50%-3rem)] p-4 rounded-xl border transition-all ${
                      isActive ? 'border-brand-500 bg-brand-50 dark:bg-brand-900/20 shadow-lg scale-105' :
                      isDone ? 'border-slate-200 dark:border-slate-700 bg-white/50 dark:bg-slate-800/50' :
                      'border-transparent opacity-50'
                    }`}>
                      <div className="flex items-center justify-between mb-1">
                        <h3 className={`font-bold text-lg ${isActive ? s.color : isDone ? 'text-slate-800 dark:text-slate-200' : 'text-slate-400'}`}>
                          {s.title}
                        </h3>
                        {isActive && <Loader2 size={16} className={`animate-spin ${s.color}`} />}
                      </div>
                      <p className="text-sm text-slate-500 dark:text-slate-400">{s.desc}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
